### ISSUE TITLE
About the the comparison method LGL in your article.

### ISSUE THREAD

**Issue by turnbacktime** [SsGood/MMGL#11]
Hello, the MMGL model you proposed is very enlightening. I would like to ask you some detailed questions about the comparative experiment in your article. When I used the LGL model to classify the ABIDE dataset, the average accuracy of the classification results obtained was close to the 86.40 marked in your article, but the variance of the results was large, nearly 7, far greater than the 1.63 marked in your article. Because the author of the original LGL model did not conduct classification experiments on ABIDE, I would like to seek your help. May I ask if it is convenient for you to provide some implementation details about the LGL model for ABIDE classification, such as the need to use recursive feature elimination to reduce the dimensionality of input features? How many graph convolutional layers were used? What is the final MLP dimension size?

**Comment by SsGood** [comment]
I'm sorry I haven't saved the hyperparameters because the baselines were run two years ago

**Comment by hetang-wang** [comment]
My LGL’s results accuracy is only about 80%.Did you make the feature selection before the data split?
