### ISSUE TITLE
关于GNN的卷积操作

### ISSUE THREAD

**Issue by hetang-wang** [SsGood/MMGL#15]
请问作者在使用GNN实现卷积的时候，是否是通过节点特征矩阵*邻接矩阵的值（邻接矩阵的值是由节点特征的相似性计算得到的）来进行消息传递和更新的，而不是与邻接节点的特征进行直接的交互？我看代码中是这样的，不确定是否理解正确。

**Comment by SsGood** [comment]
是的，当使用GCN作为GNN模型时，我们这里是直接采用了Z = AXW的计算形式，其中A是一个有权无向图。

Yes, when employing GCNs as the GNN model, we directly utilized t Z = AXW, where A represents the computed weighted undirected graph.
