### ISSUE TITLE
注意力矩阵可视化过程中遇到的问题

### ISSUE THREAD

**Issue by V50-ikun** [SsGood/MMGL#16]
你好，我运行了attn_vis.py想可视化注意力矩阵，但是它提示我找不到result中的文件，源码中也没有这个文件夹，我想知道这个问题怎么解决？
![Snipaste_2024-02-23_09-43-18](https://github.com/SsGood/MMGL/assets/131343367/24f430a5-e60a-4679-a068-469e3f4b509a)

![Snipaste_2024-02-23_09-43-30](https://github.com/SsGood/MMGL/assets/131343367/226a4a3a-addb-4313-8727-7338534f9105)

**Comment by SsGood** [comment]
感谢您的发现帮我们发现了文件中问题！这是在进行代码重梳理时的疏忽，我们遗漏了t-SNE这个必要的步骤和t-SNE结果的存储。新的代码文件将在2月26号进行更新，烦请您持续关注！

Thank you for bringing this issue to our attention. It appears to have originated during the code re-organization phase. we overlooked a crucial step concerning the implementation of t-SNE and the subsequent saving of results. 
The new code file will be released no later than February 26th. We kindly ask for your continued attention!
