### ISSUE TITLE
How to pip k-gnn？

### ISSUE THREAD

**Issue by Tengxf** [SsGood/MMGL#17]
Hello, I found that there is a package k-gnn==0.0.0 in the requirements file during installation. Could you please tell me if this is a custom package and how to install it? Wishing you a wonderful day!

**Comment by SsGood** [comment]
Sorry for the late response. The package _k-gnn_ is installed automatically by the package PyG / DGL, so you just need to install the correct version of DGL and you're done!

**Comment by Tengxf** [comment]
Thank you~

**Comment by WH12138523** [comment]
Hello, could you tell me if dgl-cu111==0.8.2 can be successfully installed via pip on your end? Is the version you selected consistent with the one provided by the author? I am unable to complete this step and hope you can help me resolve this issue. Thank you.
