### ISSUE TITLE
ABIDE datasets issue

### ISSUE THREAD

**Issue by jellyfishovo** [SsGood/MMGL#5]
when i try to run the command block:
"files = ['rois_ho']
num_subjects = 871
filemapping = {'func_preproc': 'func_preproc.nii.gz',
               'rois_ho': 'rois_ho.1D'}

if not os.path.exists(data_folder): os.makedirs(data_folder)
shutil.copyfile('./subject_IDs.txt', os.path.join(data_folder, 'subject_IDs.txt'))"
in /ABIDE/data_processing.ipynb 
it reports:FileNotFoundError: [Errno 2] No such file or directory: './subject_IDs.txt'

but i have already downloaded all the ABIDE datasets files, what should i do to run the process
Thanks!

**Comment by SsGood** [comment]
Thanks for your attention to our work!
I guess the file is already downloaded, you just need to find it and change the path. 
As shown in my data folder, subject_IDs.txt is in the directory as './ABIDE_pcp/cpac/filt_noglobal/', hope it can help you!

**Comment by jellyfishovo** [comment]
i redownloaded all the files,  but still cant find the "subject_IDs.txt", 
i wonder if this document is obtained by preprocessing instead of downloading it beacause all i have downloaded are ".1D" files and a Phenotypic_V1_0b_preprocessed1.csv

Thanks!

**Comment by SsGood** [comment]
Thanks for your help to find this problem and I will recheck and update the corresponding codes! 
Back to our question again, the preprocessing code of ABIDE is borrowed from [popGCN](https://github.com/parisots/population-gcn), so you may be able to solve your problem from the original code.
