### ISSUE TITLE
ABIDE datasets issue 

### ISSUE THREAD

**Issue by Pttery** [SsGood/MMGL#6]
运行 feat_256_1 = feature_selection(features, label, train_index, 256)函数时
报__init__() takes 2 positional arguments but 3 positional arguments (and 2 keyword-only arguments) were given
我查到的时参数不匹配，但由于调用的是封装函数，我想的可能是sklearn版本不对，请问作者的sklearn版本是多少？

**Comment by SsGood** [comment]
不好意思我们没有交代清楚sklearn的版本，您可以试一下scikit-learn == 0.19.1

I'm sorry for that, maybe you can run the codes again under scikit-learn == 0.19.1
